package droid.maxaria.maxander.simplehoroscope

const val ZODIAC="zodiac_sign"
const val PREDICT="predict"
const val ERROR_String ="Error"
const val ARIES_ID="aries"
const val TAURUS_ID="taurus"
const val GEMINI_ID="gemini"
const val CANCER_ID="cancer"
const val LEO_ID="leo"
const val VIRGO_ID="virgo"
const val LIBRA_ID="libra"
const val SCORPIO_ID="scorpio"
const val SAGITTARIUS_ID="sagittarius"
const val CAPRICORNUS_ID="capricorn"
const val AQUARIUS_ID="aquarius"
const val PISCES_ID="pisces"